### PR TITLE
minor ports from matlab to python (re: cases with no repeats; new FIR summary voxel viz)

### PR DESCRIPTION
**Pull request by jacob-prince**
these two new commits contain ports of the following commits of matlab code made by @kendrickkay 

371754299834852bc31eae126f63cee97441d068: making sure dmetric is nan if no repeats
881b5a31c917462027e30e210c0042c718969db5: adding warnings if no repeats
31f9eaa46e6f8c01cde49315826a0aef5cc674f1: runwise_FIR summary voxel visualization
3c0c435ca3bf34e3e37ef6d3c6229d263a881ca9: adding sanity check to prevent conds occurring at same time.

for some reason there is weirdness with whitespace in the commit of glmsingle.py; I will try to avoid this in future commits. would recommend using "ignore whitespace" to review the code.

### CODE REVIEW

**Comment by kendrickkay** [comment]
Oh, I see the "ignore whitespace" button.  Cool.

**Review by kendrickkay — APPROVED** [review]
Looks good

**Comment by kendrickkay** [comment]
I wouldn't worry about trying to avoid the whitespace stuff in the future since the little button makes it all fine.

**Comment by jacob-prince** [comment]
Yeah, I should have just made sure to "discard all changes" before editing any part of the code. Now I know. That will prevent whitespace issues moving forward.

**Comment by iancharest** [comment]
Do we know if this still works with our tests?

**Comment by jacob-prince** [comment]
I am working on developing proper suites of unit test cases as we have discussed. In the meantime, I am testing these ports primarily using example01 dataset. For each commit, I modify the data to test whatever feature is being implemented. For example by messing with the design matrix to trigger the error associated with having two conditions  at the same onset time. If you'd prefer, we can hold off on merging until I have more fully expanded the unit tests. And/or, please suggests additional tests I should run at this time...

**Comment by kendrickkay** [comment]
I think you can/should go ahead and do the merge.   The fuller test suite stuff can come later.   

Jacob and Ian, if you recall, we do have a "manual" test suite that I had run in the past on 10+ (small-scale) datasets.  Jacob, when you are ready, we can go over how that is set up if you have forgotten.

**Comment by jacob-prince** [comment]
I have added a few commits that handle all the extra_regressors functionality. let me know if things look good and I will merge.

**Pull request merged**
